# Generated by Django 5.2.7 on 2025-11-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
