# Generated by Django 5.2.7 on 2026-01-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_khqr_md5_order_khqr_qr_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_paid_notified',
            field=models.BooleanField(default=False),
        ),
    ]
